### ISSUE TITLE
buidler-gas-reporter doesn't work out of box with openzeppelin proxies, but eth-gas-reporter do

### ISSUE THREAD

**Issue by wmitsuda** [cgewecke/buidler-gas-reporter#12]
In my tests, running the eth-gas-reporter out of box with truffle in a project that uses openzeppelin proxies just works fine, besides the warnings in the advanced section.

But running the same tests in a buidler project, using the buidler-gas-reporter plugin, doesn't report any function names.

I've created a small project that reproduces this issue; it is configured both with eth-gas-reporter and buidler-gas-reporter:

https://github.com/wmitsuda/reproduce-buidler-gas-reporter

If you run it using `npm run gas-reporter-test` it works fine using truffle + eth-gas-reporter under the hood.

If you run it using `npm run buidler-reporter-test`, it uses buidler + buidler-gas-reporter and doesn't show any function names.

**Comment by vnavascues** [comment]
Hi @wmitsuda 

Where you able to figure out a solution? I'm interested because I'm facing the same issue with the same stack (buidler + buidler eth-gas-reporter + OZ upgrades contracts).

Thanks!

**Comment by wmitsuda** [comment]
> Hi @wmitsuda
> 
> Where you able to figure out a solution? I'm interested because I'm facing the same issue with the same stack (buidler + buidler eth-gas-reporter + OZ upgrades contracts).
> 
> Thanks!

No, I didn't, but I haven't researched more since then.

**Comment by nmclrn** [comment]
@wmitsuda @vnavascues The demo repo won't run tests successfully at all, let alone report gas, but it looks like the `npm run buidler-reporter-test` command might be missing the `--network localhost` option recommended [here](https://github.com/cgewecke/buidler-gas-reporter), just in case that's the issue and the OZ stuff was a red herring.

**Comment by vnavascues** [comment]
@wmitsuda @nmclrn thanks for the prompt replies.

@nmclrn you were right, OZ upgrades is a red herring and I wasn't properly adding the `--network localhost`, despite being well indicated in this repo documentation.

**Comment by cgewecke** [comment]
Side-note, in `0.1.4` the independent node requirement is gone. Hopefully this "just works" now without having to pore through the docs / set up everything differently than normal.

Closing because this seems to have been a setup issue with the client. Please just lmk if there's more to be investigated here.
