### ISSUE TITLE
buidler-gas-reporter table incomplete (using buidler node as server)

### ISSUE THREAD

**Issue by gitpusha** [cgewecke/buidler-gas-reporter#14]
Hi @cgewecke .

Yesterday, I wanted to configure `buidler-gas-reporter` for the first time.

The first gotcha for me was that I had to spin up `npx buidler node` in order for the `buidler-gas-reporter` overriden `npx buidler test` command to work and connect to the localhost network properly. When I naively tried running `npx buidler test` by itself I had gotten this error `Error: connect ECONNREFUSED 127.0.0.1:8545`.

However, once I ran the buidler node the test suite was run. 

Now I am stuck with this incomplete test table however:

![buidler-gas-reporter](https://user-images.githubusercontent.com/36712489/80346840-b3582d00-886b-11ea-8c73-c974a9b7691c.jpeg)

**Do you know what's going on here and how I can fix it?**

I can't wait to use `buidler-gas-reporter` with `codechecks` in our CI.

Reproduce:
- `usePlugin("buidler-gas-reporter")`
- `npx buidler node`
- `npx buidler test`

Environment:
- buidler repo:
    "@nomiclabs/buidler": "1.2.0",
    "@nomiclabs/buidler-ethers": "1.2.0",
    "@nomiclabs/buidler-waffle": "1.2.0",
    "buidler-gas-reporter": "^0.1.3",
    "ethers": "4.0.47",
- macOS Catalina 10.15.3

**Comment by cgewecke** [comment]
Hi @gitpusha thanks for reporting, 

Would it be possible to show your buidler.config.js too? 

cf: [synthetix 503][1]

[1]: https://github.com/Synthetixio/synthetix/pull/503

**Comment by gitpusha** [comment]
Yep - here is an excerpt
```javascript
module.exports = {
  defaultNetwork: DEFAULT_NETWORK ? DEFAULT_NETWORK : "buidlerevm",
  networks: {
    buidlerevm: {
      hardfork: "istanbul",
      contracts: buidlerevmConfig.contracts,
      gas: 15000000,
      blockGasLimit: 20000000,
      // Custom
      filters: { defaultFromBlock: 1 },
    },
    coverage: {
      url: "http://127.0.0.1:8555",
      // Custom
      filters: { defaultFromBlock: 1 },
    },
    mainnet: {
      // Standard
      accounts: { mnemonic: MAINNET_MNEMONIC },
      chainId: 1,
      gas: "auto",
      gasPrice: parseInt(utils.parseUnits("5", "gwei")),
      gasMultiplier: 1.5,
      url: `https://mainnet.infura.io/v3/${INFURA_ID}`,
      // Custom
      addressBook: mainnetConfig.addressBook,
      contracts: mainnetConfig.contracts,
      deployments: mainnetConfig.deployments,
      filters: mainnetConfig.filters,
    },
    kovan: {
      // Standard
      accounts: { mnemonic: DEV_MNEMONIC },
      chainId: 42,
      gasPrice: parseInt(utils.parseUnits("1", "gwei")),
      url: `https://kovan.infura.io/v3/${INFURA_ID}`,
      // Custom
      addressBook: kovanConfig.addressBook,
      contracts: kovanConfig.contracts,
      deployments: kovanConfig.deployments,
      filters: kovanConfig.filters,
    },
    rinkeby: {
      // Standard
      accounts: { mnemonic: DEV_MNEMONIC },
      chainId: 4,
      gasPrice: parseInt(utils.parseUnits("8", "gwei")),
      url: `https://rinkeby.infura.io/v3/${INFURA_ID}`,
      // Custom
      addressBook: rinkebyConfig.addressBook,
      contracts: rinkebyConfig.contracts,
      deployments: rinkebyConfig.deployments,
      filters: rinkebyConfig.filters,
    },
  },
  solc: {
    version: "0.6.6",
    optimizer: { enabled: true },
  },
};

// ================================= PLUGINS =========================================
// buidler-ethers
usePlugin("@nomiclabs/buidler-ethers");
// buidler-waffle
usePlugin("@nomiclabs/buidler-waffle");
// solidity-coverage
usePlugin("solidity-coverage");
```

**Comment by gitpusha** [comment]
Also I wanted to ask: is solidity-coverage also run with buidler-gas-reporter once I have the gas-reporter configured? Or is the `npx buidler coverage` command not affected by the `npx buidler test` task which is overridden by the gas-reporter? I would like for gas-reports to only be run on my normal test suite, and not for coverage too.

**Comment by cgewecke** [comment]
Actually, you cannot run them together...the gas reporter locks up the coverage tools provider. This is another bug (reported at [solidity-coverage 500][1]). Will address both of these and publish here and at SC. 

[1]: https://github.com/sc-forks/solidity-coverage/issues/500

**Comment by cgewecke** [comment]
@gitpusha 
Was able to get the gas-reporter [working][1] with an independent node in tests added for #17. 

The big difference I see between the config here and yours is:
+ network is `localhost` (the independent node default)
  + e.g. `npx buidler test --network localhost
+ no `contracts` key in the network. 

(Is `contracts` a custom property you're adding? I can't find it in the buidler docs.)

The gas-reporter expects contract artifacts to be located at whatever buidler's `config.paths.artifacts` path is. Are they stored elsewhere in your project?

[1]: https://travis-ci.org/github/cgewecke/buidler-gas-reporter/builds/681338372#L351-L368

**Comment by cgewecke** [comment]
The interaction bug between buidler-gas-reporter and solidity-coverage should be fixed in the latest solidity-coverage: `0.7.5`.

**Comment by gitpusha** [comment]
> (Is contracts a custom property you're adding? I can't find it in the buidler docs.)

Yes, it is just a custom array of contract names I import. I do not override the artifacts path here in any way.

I will try again with `npx buidler test --network localhost` and report back.

> The interaction bug between buidler-gas-reporter and solidity-coverage should be fixed in the latest solidity-coverage: 0.7.5

To rephrase my original question regarding this: I would like to run the buidler-gas-reporter only when I run `npx buidler test` and not a second time for `npx buidler coverage`. When I use the `buidler-gas-reporter` plugin alongside `solidity-coverage`, will the gas-reporter be automatically run for both or is this somehow opt-in. If it is automatically opt-in, I would like to opt-out for the coverage.

**Comment by gitpusha** [comment]
@cgewecke 
- `npx buidler node`
-`npx buidler test --network localhost`

works! I get a neat gas report. Thank you!

I just also ran a my coverage with 0.7.5 and the buidler-gas-reporter plugin enabled, and saw that no report was produced for the coverage run, which is what I want anyway, so all good. 

I can close this issue. Thanks for helping out.

**Comment by gitpusha** [comment]
@cgewecke maybe as a follow-up question. Since `buidler-gas-reporter` overrides the `npx buidler test` task, I have not found an easy way to run my test suite without the gas-reporter and its current need for a buidler node process running on localhost.

**Is it still possible to explicitly run my buidler test suite without the gas-reporter, while this plugin is enabled?**

**Comment by cgewecke** [comment]
@gitpusha Yes,

In the [gasReporter config options][1]  there is an `enabled` flag you can toggle on and off using environment variables. 

(Not sure what developments there have been on the buidler side but when this module was written, it was not possible for a "overriding" plugin to add its own  command line options. That would be ideal.)

[1]: https://github.com/cgewecke/buidler-gas-reporter#configuration

**Comment by gitpusha** [comment]
Sorry I actually read about this config options in the docs and had forgotten about it. Thanks for answering diligently.
