### ISSUE TITLE
Localhost requirement seems incompatible with bevm callstacks?

### ISSUE THREAD

**Issue by nmclrn** [cgewecke/buidler-gas-reporter#29]
The requirement to run `buidlerevm` with the `--network localhost` option seems to be a (known limitation)[https://github.com/cgewecke/buidler-gas-reporter/commit/2d36ad6198916438d3c027f347dc960c720f3809].

Does this requirement make gas usage reports incompatible with solidity callstacks? I can't seem to get both working at the same time. If true, that may be worth clarifying in the docs and perhaps recommending that `usePlugin("buidler-gas-reporter")` is called _conditionally_.

**Comment by cgewecke** [comment]
Hi @nmclrn, @chanhosuh 

With `0.1.4` (just released), the independent node requirement is gone. You should be able to run the reporter using regular BuidlerEVM and I believe stack traces will appear as expected. 

It should also be noticeably faster. 

Closing here, please just lmk if you run into any problems / bugs when upgrading...
