### ISSUE TITLE
Missing built files in npm

### ISSUE THREAD

**Issue by alcuadrado** [cgewecke/buidler-gas-reporter#4]
Hi @cgewecke! Congratulations on shipping this plugin! 🎉

Unfortunately, it isn't working right now. I think you forgot to build the project before running `npm publish`, because the `dist/` folder is missing. I guess compiling and publishing a patch version should be enough.

I can't believe `npm` doesn't fail to publish a package whose `main` doesn't exist. I'll try to do something about this in the plugin boilerplate project.

**Comment by cgewecke** [comment]
Oh my! Very sorry, thanks for catching this. I published late last night and completely forgot about building. 

This is fixed in `0.1.1`.

**Comment by alcuadrado** [comment]
Thanks for the quick fix!

Does it work with ethers? Or do I need `@nomiclabs/buidler-truffle5`?

**Comment by cgewecke** [comment]
@alcuadrado Yes, ethers works:

![Screen Shot 2019-07-03 at 3 28 25 PM](https://user-images.githubusercontent.com/7332026/60628666-56086200-9da7-11e9-9ef3-6dd61e168ad7.png)

I had difficulty getting my ethers project tests to work (in this plugin, not yours). It's a little tricky to test the test command - opening an issue about that rn.

**Comment by cgewecke** [comment]
Ah wait - there's a problem! Methods weren't picked up. I have to look at why.
