### ISSUE TITLE
Ethers project methods not being picked up in report

### ISSUE THREAD

**Issue by cgewecke** [cgewecke/buidler-gas-reporter#6]
See [this comment](https://github.com/cgewecke/buidler-gas-reporter/issues/4#issuecomment-508276395)

**Comment by cgewecke** [comment]
`0.1.2`

![Screen Shot 2019-07-04 at 4 23 30 PM](https://user-images.githubusercontent.com/7332026/60689978-35f4a380-9e78-11e9-9c9f-702af0c3848b.png)

**Comment by alcuadrado** [comment]
That's great! Thanks!
